web/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("signin/", views.SigninView.as_view(), name="signin"),
    path("signout/", views.SignoutView.as_view(), name="signout"),
]

web/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(url=reverse_lazy("todos:index")), name="top"),
    path("admin/", admin.site.urls, name="admin"),
    path("accounts/", include("accounts.urls"), name="accounts_app"),
    path("todos/", include("todos.urls"), name="todos_app"),
]

# Add debug toolbar
if settings.DEBUG:
    import debug_toolbar  # type: ignore [import]

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

web/todos/urls.py
from django.urls import path

from . import views

app_name = "todos"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("create/", views.TodoCreateView.as_view(), name="create"),
    path("<uuid:pk>/", views.TodoDetailView.as_view(), name="detail"),
    path("update/<uuid:pk>/", views.TodoUpdateView.as_view(), name="update"),
    path("delete/<uuid:pk>/", views.TodoDeleteView.as_view(), name="delete"),
]

web/todos/models.py
import uuid

from django.conf import settings
from django.db import models


class StatusChoices(models.TextChoices):
    TODO = "01", "Todo"
    DOING = "02", "Doing"
    DONE = "03", "Done"


class Todo(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user_todos"
    )
    title = models.CharField(
        max_length=100,
    )
    description = models.TextField(max_length=400, null=True, blank=True)
    status = models.CharField(
        max_length=2,
        choices=StatusChoices.choices,
        default=StatusChoices.TODO,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "todo"
        verbose_name_plural = "todos"

web/todos/forms.py
from django.forms import ModelForm

from .models import Todo


class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ["title", "description"]

web/accounts/views.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.views import LoginView as BaseSigninView
from django.contrib.auth.views import LogoutView as BaseSignoutView
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView


class IndexView(TemplateView):
    template_name = "accounts/index.html"


class SignupView(CreateView):
    form_class = UserCreationForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("accounts:index")


class SigninView(BaseSigninView):
    form_class = AuthenticationForm
    template_name = "accounts/signin.html"


class SignoutView(BaseSignoutView):
    success_url = reverse_lazy("accounts:index")

web/todos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import AnonymousUser
from django.db.models import QuerySet
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from .forms import TodoForm
from .models import Todo


class IndexView(LoginRequiredMixin, ListView):
    template_name = "todos/index.html"
    context_object_name = "todo_list"
    model = Todo

    def get_queryset(self) -> QuerySet[Todo]:
        user = self.request.user
        if isinstance(user, AnonymousUser):
            return Todo.objects.none()
        else:
            return Todo.objects.filter(user=user)


class TodoDetailView(LoginRequiredMixin, DetailView):
    template_name = "todos/detail.html"
    context_object_name = "todo"
    model = Todo


class TodoCreateView(LoginRequiredMixin, CreateView):
    form_class = TodoForm
    template_name = "todos/create.html"
    success_url = reverse_lazy("todos:index")

    def form_valid(self, form: TodoForm) -> HttpResponse:
        form.instance.user = self.request.user
        return super().form_valid(form)


class TodoUpdateView(LoginRequiredMixin, UpdateView):
    form_class = TodoForm
    model = Todo
    template_name = "todos/update.html"
    success_url = reverse_lazy("todos:index")


class TodoDeleteView(LoginRequiredMixin, DeleteView):  # type: ignore [misc]
    template_name = "todos/delete.html"
    context_object_name = "todo"
    success_url = reverse_lazy("todos:index")
    model = Todo

web/accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block title %}
    Account|MyPage
{% endblock %}

{% block content %}
    <div>
        {% if user.is_authenticated %}
            <h1>Welcome To ExampleApp.</h1>
            <p>Username: {{ user.username }}</p>
            <a href="{% url 'todos:index' %}">Todo</a> 
            <a href="{% url 'accounts:signout' %}">Signout</a> 
        {% else %}
            <h1>Guest User</h1>
            <a href="{% url 'accounts:signup' %}">Signup</a>
            <a href="{% url 'accounts:signin' %}">Signin</a>
        {% endif %}
    </div>
{% endblock %}

web/accounts/templates/accounts/signin.html
{% extends 'base.html' %}

{% block title %}
    Account|SignIn
{% endblock %}

{% block content %}
    <div>
        <h1>SignIn Page</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
                {{ field.label }}
                {{ field }}
                {{ field.errors }}
                <br/>
            {% endfor %}
            <button type="submit">SignIn</button>
        </form>
        <button type="button" onclick="history.back()">Back</button>
    </div>
{% endblock %}

web/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}
    Account|SignUp
{% endblock %}

{% block content %}
    <div>
        <h1>SignUp Page</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
                {{field.label }}
                {{ field }}
                {{ field.errors }}
                <br/>
            {% endfor %}
            <button type="submit">SignUp</button>
        </form>
        <button type="button" onclick="history.back()">Back</button>
    </div>
{% endblock %}

web/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}
    {% endblock %}
</title>
</head>

<body>
    {% block content %}
    {% endblock %}
</body>

</html>

web/todos/templates/todos/create.html
{% extends 'base.html' %}

{% block title %}
    Todo|Create
{% endblock %}

{% block content %}
    <div>
        <h1>Create Todo</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
                {{ field.label }}
                {{ field }}
                {{ field.errors }}
                <br/>
            {% endfor %}
            <button type="submit">Create</button>
        </form>
        <button type="button" onclick="history.back()">Back</button>
    </div>
{% endblock %}

web/todos/templates/todos/delete.html
{% extends 'base.html' %}

{% block title %}
    Todo|Delete
{% endblock %}

{% block content %}
    <div>
        <form method="POST">
            {% csrf_token %}
            <p>Are you sure you want to permanently delete this Todo({{todo.pk}})</p>
            <input type="submit" value="Delete">
        </form>
        <button type="button" onclick="history.back()">Back</button>
    </div>
{% endblock %}

web/todos/templates/todos/detail.html
{% extends 'base.html' %}

{% block title %}
    Todo|Detail
{% endblock %}

{% block content %}
    <div>
        <h1>Detail Todo</h1>
        <p>id: {{todo.pk}}</p>
        <p>title: {{todo.title}}</p>
        <p>description: {{todo.description}}</p>
        <p>status: {{todo.get_status_display}}</p>
        <p>created date: {{todo.created_at|date:'Y/m/d H:i:s A T'}}</p>
        <a href="{% url 'todos:update' todo.pk %}">Update</a>
        <a href="{% url 'todos:delete' todo.pk %}">Delete</a>
        <button type="button" onclick="history.back()">Back</button>
    </div>
{% endblock %}

web/todos/templates/todos/index.html
{% extends 'base.html' %}

{% block title %}
    Todo|List
{% endblock %}

{% block content %}
    <div>
        <h1>TodoList Page</h1>
        <a href="{% url 'accounts:index' %}">Accounts</a>
        <a href="{% url 'todos:create' %}">Create</a>
        {% for todo in todo_list %}
            <p>{{todo.user.username}}</p>
            <p>{{todo.title}}:{{todo.get_status_display}}</p>
            <p>{{todo.status}}</p>
            <a href="{% url 'todos:detail' todo.pk %}">detail</a>
        {% endfor %}
    </div>
{% endblock %}

web/todos/templates/todos/update.html
{% extends 'base.html' %}

{% block title %}
    Todo|Update
{% endblock %}

{% block content %}
    <div>
        <h1>Update Todo</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
                {{ field.label }}
                {{ field }}
                {{ field.errors }}
                <br/>
            {% endfor %}
            <button type="submit">Update</button>
        </form>
        <button type="button" onclick="history.back()">Back</button>
    </div>
{% endblock %}